### PR TITLE
Adds Button, Reserve Feature and Equipment List

### PR DESCRIPTION
**Pull request by kingsrf**
Fixes issues #14 #15

### CODE REVIEW

**Review by faayiti — COMMENTED** [review]
The web site looks appealing, good job King!

**Review by faayiti — APPROVED** [review]

**Review by faayiti — APPROVED** [review]
The website looks interesting, Great job King!

**Review by faayiti — COMMENTED** [review]
good job!

**Review by faayiti — APPROVED** [review]
The website looks good!

**Comment by kingsrf** [comment]
To solve conflicts

**Pull request closed without merging**
